export {default as LandingPage} from './LandingPage/LandingPage'
export {default as Signin} from './Signin/Signin'
export {default as SingleDonation} from './SingleDonation/SingleDonation'
export {default as CreateProject} from './CreateProject/CreateProject'
export {default as ProfileInfo} from './ProfileInfo/ProfileInfo'